# -*- coding: utf-8 -*-
"""FinalProject

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bl0BUbuK4DIWzItjMOWNq81LMTOyEjzO
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import classification_report, accuracy_score

# --------- ฟังก์ชันจัดการข้อมูล ---------
def merge_sort(arr):
    if len(arr) > 1:
        mid = len(arr) // 2
        left_half = arr[:mid]
        right_half = arr[mid:]
        merge_sort(left_half)
        merge_sort(right_half)
        i = j = k = 0
        while i < len(left_half) and j < len(right_half):
            if left_half[i][5] < right_half[j][5]:  # ใช้คะแนนรวม (index 5)
                arr[k] = left_half[i]
                i += 1
            else:
                arr[k] = right_half[j]
                j += 1
            k += 1
        while i < len(left_half):
            arr[k] = left_half[i]
            i += 1
            k += 1
        while j < len(right_half):
            arr[k] = right_half[j]
            j += 1
            k += 1

def jump_search(arr, target_id):
    n = len(arr)
    step = int(np.sqrt(n))
    prev = 0
    while prev < n and arr[min(step, n)-1][1] < target_id:
        prev = step
        step += int(np.sqrt(n))
        if prev >= n:
            return -1
    while prev < n and arr[prev][1] < target_id:
        prev += 1
        if prev == min(step, n):
            return -1
    if prev < n and arr[prev][1] == target_id:
        return prev
    return -1

def display_data(data):
    print("\nรายชื่อนักเรียน:")
    for s in data:
        print(f"{s[0]} ({s[1]}): Score={s[5]}, Study={s[3]}hr, Absence={s[4]}, Group={s[6]}")

# --------- ตั้งค่าข้อมูลเริ่มต้นและโมเดล ---------
class_names = ['Weak', 'Average', 'Good']
raw_data = np.array([
    [30, 1, 14],
    [49, 2, 13],
    [43, 2, 13],
    [55, 3, 12],
    [54, 4, 11],
    [62, 5, 10],
    [68, 6, 9],
    [71, 7, 8],
    [75, 8, 7],
    [79, 9, 6],
    [82, 11, 4],
    [86, 10, 5],
    [91, 12, 3],
    [95, 14, 1],
    [97, 15, 0],
])
y = np.array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1,  2, 2, 2, 2, 2])

X_train, X_test, y_train, y_test = train_test_split(raw_data, y, test_size=0.4, random_state=42, stratify=y)
model = SVC(kernel='linear')
model.fit(X_train, y_train)

# --------- ฟังก์ชันจัดกลุ่ม ---------
def get_group(score, hours, absences):
    pred = model.predict([[score, hours, absences]])
    return class_names[pred[0]]

# --------- ฟังก์ชันนำเข้าข้อมูลเบื้องต้นจาก Excel ---------
def initial_import_excel():
    global students, model, X_train, X_test, y_train, y_test
    students = []
    while True:
        try:
            file_path = input("กรุณาใส่ชื่อไฟล์ Excel (.xlsx): ")
            df = pd.read_excel(file_path)

            required_cols = ['Name', 'ID', 'Score', 'StudyHours', 'Absences', 'Group']
            if not all(col in df.columns for col in required_cols):
                print("ไฟล์ต้องมีคอลัมน์: Name, ID, Score, StudyHours, Absences, Group")
                continue

            X = []
            y = []
            count = 0

            for _, row in df.iterrows():
                name = str(row['Name'])
                sid = str(row['ID'])
                score = float(row['Score'])
                hours = float(row['StudyHours'])
                absn = float(row['Absences'])
                group_label = str(row['Group'])

                if any(s[1] == sid for s in students):
                    print(f"รหัสซ้ำ: {sid} ข้ามรายการนี้")
                    continue

                if group_label not in class_names:
                    print(f"กลุ่มไม่ถูกต้อง: {group_label} ข้ามรายการนี้")
                    continue

                group_index = class_names.index(group_label)

                students.append([name, sid, score, hours, absn, score, group_label])
                X.append([score, hours, absn])
                y.append(group_index)
                count += 1

            X = np.array(X)
            y = np.array(y)

            # แยกชุดข้อมูล train/test และฝึก SVM
            X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=42, stratify=y)
            model = SVC(kernel='linear')
            model.fit(X_train, y_train)

            print(f"\nนำเข้าข้อมูลและฝึกโมเดลสำเร็จ {count} รายการ!\n")
            break

        except Exception as e:
            print("เกิดข้อผิดพลาดขณะนำเข้าไฟล์:", e)


# --------- ฟังก์ชันเมนูหลัก ---------
def main_menu():
    while True:
        print("\n==== ระบบจัดการข้อมูลนักเรียน ====")
        print("1. เรียงลำดับคะแนน")
        print("2. ค้นหานักเรียนตามรหัส")
        print("3. เพิ่มนักเรียนใหม่")
        print("4. แสดงข้อมูลทั้งหมด")
        print("5. ประเมินผล SVM ใหม่")
        print("6. นำเข้าข้อมูลจาก Excel (.xlsx)")
        print("7. ออกจากโปรแกรม")

        choice = input("เลือกเมนู (1-7): ")

        if choice == "1":
            merge_sort(students)
            print("เรียงลำดับเรียบร้อยแล้ว!")
            display_data(students)

        elif choice == "2":
            search_student_by_id()

        elif choice == "3":
            add_new_student()

        elif choice == "4":
            display_data(students)

        elif choice == "5":
            evaluate_svm_model()

        elif choice == "6":
            import_from_excel()

        elif choice == "7":
            print("จบการทำงาน")
            break

        else:
            print("เลือกเมนูไม่ถูกต้อง กรุณาลองใหม่")

def search_student_by_id():
    id_to_search = input("กรอกรหัสนักเรียน: ")
    students_sorted = sorted(students, key=lambda x: x[1])
    idx = jump_search(students_sorted, id_to_search)
    if idx != -1:
        s = students_sorted[idx]
        print(f"พบ {s[0]} ({s[1]}) คะแนนรวม {s[5]} กลุ่ม: {s[6]}")
    else:
        print("ไม่พบรหัสนักเรียนนี้")

def add_new_student():
    name = input("ชื่อนักเรียน: ")
    sid = input("รหัสนักเรียน: ")
    try:
        score = float(input("คะแนนรวม (0-100): "))
        hours = float(input("ชั่วโมงเรียน/สัปดาห์: "))
        absn = float(input("จำนวนวันที่ขาดเรียน: "))
        group = get_group(score, hours, absn)
        students.append([name, sid, score, hours, absn, score, group])
        print("เพิ่มข้อมูลเรียบร้อย!")
    except ValueError:
        print("กรอกข้อมูลไม่ถูกต้อง")

def evaluate_svm_model():
    print("===== ทดสอบโมเดล SVM =====")
    y_pred = model.predict(X_test)
    print("Accuracy:", accuracy_score(y_test, y_pred))
    print(classification_report(y_test, y_pred, target_names=class_names, zero_division=1))

    # แสดงผลกราฟ Train/Test
    plt.figure(figsize=(10, 6))
    for i, cname in enumerate(class_names):
        plt.scatter(X_train[y_train == i][:, 1], X_train[y_train == i][:, 0], label=f"{cname} (Train)", marker='o')
        plt.scatter(X_test[y_test == i][:, 1], X_test[y_test == i][:, 0], label=f"{cname} (Test)", marker='x')
    plt.xlabel("Study Hours / Week")
    plt.ylabel("Score")
    plt.title("SVM Classification (Train/Test)")
    plt.legend()
    plt.grid(True)
    plt.show()

    print("\n===== ทดสอบโมเดลกับข้อมูลของคุณ =====")
    try:
        score = float(input("กรอก Score (0-100): "))
        study_hours = float(input("กรอกชั่วโมงเรียนต่อสัปดาห์: "))
        absences = float(input("กรอกจำนวนวันขาดเรียน: "))

        user_input = np.array([[score, study_hours, absences]])
        prediction = model.predict(user_input)
        print(f"\nกลุ่มผลการเรียนที่คาดการณ์: {class_names[prediction[0]]}")

        # วาดกราฟผลลัพธ์พร้อมแบ่งโซนพื้นหลัง
        plt.figure(figsize=(12, 8))
        h = 0.5
        x_min, x_max = raw_data[:, 1].min() - 1, raw_data[:, 1].max() + 1
        y_min, y_max = raw_data[:, 0].min() - 5, raw_data[:, 0].max() + 5

        xx, yy = np.meshgrid(np.arange(x_min, x_max, h),
                             np.arange(y_min, y_max, h))

        dummy_absences = np.full(xx.ravel().shape, raw_data[:, 2].mean())
        Z = model.predict(np.c_[yy.ravel(), xx.ravel(), dummy_absences])
        Z = Z.reshape(xx.shape)

        plt.contourf(xx, yy, Z, alpha=0.3, cmap=plt.cm.coolwarm)

        for i, cname in enumerate(class_names):
            plt.scatter(raw_data[y == i][:, 1], raw_data[y == i][:, 0], label=cname, marker='o')

        plt.scatter(study_hours, score, color='red', label='Your Input', marker='*', s=300)

        plt.xlabel('Study Hours / Week')
        plt.ylabel('Score')
        plt.title('Student Group Classification with Score Zones')
        plt.legend()
        plt.grid(True)
        plt.show()

    except Exception as e:
        print("เกิดข้อผิดพลาดระหว่างรับข้อมูล: ", e)

def import_from_excel():
    try:
        file_path = input("กรอกชื่อไฟล์ Excel (.xlsx): ")
        df = pd.read_excel(file_path)

        required_cols = ['Name', 'ID', 'Score', 'StudyHours', 'Absences']
        if not all(col in df.columns for col in required_cols):
            print("ไฟล์ต้องมีคอลัมน์: Name, ID, Score, StudyHours, Absences")
        else:
            count = 0
            for _, row in df.iterrows():
                name = str(row['Name'])
                sid = str(row['ID'])
                score = float(row['Score'])
                hours = float(row['StudyHours'])
                absn = float(row['Absences'])
                if any(s[1] == sid for s in students):
                    print(f"รหัสซ้ำ: {sid} ข้ามรายการนี้")
                    continue
                group = get_group(score, hours, absn)
                students.append([name, sid, score, hours, absn, score, group])
                count += 1
            print(f"นำเข้าข้อมูลสำเร็จ {count} รายการ!")
    except Exception as e:
        print("เกิดข้อผิดพลาดขณะนำเข้าไฟล์:", e)

# --------- เรียกใช้งานเริ่มต้น ---------
initial_import_excel()
main_menu()

